[tool.poetry]
name = "notionapi"
version = "0.1.0"
description = ""
authors = ["Frank <sungwoo@treenod.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
notion-client = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
